# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version, and other tools you might need
build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  jobs:
    pre_build:
      - curl -L https://dot.net/v1/dotnet-install.sh -o dotnet-install.sh
      - chmod +x dotnet-install.sh
      - ./dotnet-install.sh --channel 10.0 --install-dir "$HOME/.dotnet"
      - ./dotnet-install.sh --channel 8.0 --install-dir "$HOME/.dotnet"
      - DOTNET_ROOT="$HOME/.dotnet" PATH="$PATH":"$HOME/.dotnet":"$HOME/.dotnet/tools" tools/generate-csharp-doc.sh
      - DOTNET_ROOT="$HOME/.dotnet" PATH="$PATH":"$HOME/.dotnet":"$HOME/.dotnet/tools" tools/generate-envvars-doc.sh

# Move anchors out of the titles
# Build documentation in the ".docs/" directory with Sphinx
sphinx:
   configuration: .docs/conf.py

     # Optionally, but recommended,
# declare the Python requirements required to build your documentation
# See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
   install:
   - requirements: .docs/requirements.txt

