#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["Compute/PollingAgent/src/ArmoniK.Core.Compute.PollingAgent.csproj", "Compute/PollingAgent/src/"]
COPY ["Adaptors/Redis/src/ArmoniK.Core.Adapters.Redis.csproj", "Adaptors/Redis/src/"]
COPY ["Common/src/ArmoniK.Core.Common.csproj", "Common/src/"]
COPY ["Adaptors/Amqp/src/ArmoniK.Core.Adapters.Amqp.csproj", "Adaptors/Amqp/src/"]
COPY ["Adaptors/MongoDB/src/ArmoniK.Core.Adapters.MongoDB.csproj", "Adaptors/MongoDB/src/"]
RUN dotnet restore "Compute/PollingAgent/src/ArmoniK.Core.Compute.PollingAgent.csproj"
COPY . .
WORKDIR "/src/Compute/PollingAgent/src"
RUN dotnet build "ArmoniK.Core.Compute.PollingAgent.csproj" -c Release -o /app/build

WORKDIR /app/build
RUN dotnet tool install --global dotnet-trace
#ENTRYPOINT ["dotnet", "run", "-c Release", "--no-restore", "--no-build", "-- collect"]
ENTRYPOINT ["/root/.dotnet/tools/dotnet-trace", "collect", "--output", "/trace/polling.nettrace", "--profile", "gc-verbose", "--duration", "00:05:00", "--", "dotnet", "ArmoniK.Core.Compute.PollingAgent.dll"]