// This file is part of the ArmoniK project. Copyright (C) ANEO, 2021-2026.
// SPDX-License-Identifier: AGPL-3.0-or-later

//! Hasher of the hot-path tables (mirrors, node and key indexes): FxHash, the fastest
//! measured (benches/compare-hashers.sh), and unseeded.
//!
//! An unseeded hasher lets whoever chooses the keys forge collisions and turn table
//! lookups into linear scans. That is acceptable here because nobody outside ArmoniK Core
//! chooses them: the largest tables, the mirrors, hold hashes of data identifiers, which
//! are GUIDs generated by Core, hashed by the adapter with FNV-1a and fmix64, hence
//! uniformly spread; key names are session identifiers, also generated by Core; node
//! identifiers come from the deployment. Only a client reaching the broker directly could
//! send crafted hashes, and such a client can already do worse (acknowledge the tasks of
//! others, flood a partition): the broker is protected by restricting who reaches it,
//! mutual TLS in production, not by its hasher. Should these keys ever come from users,
//! switch back to a seeded hasher (foldhash was 10 to 40 % slower on the scheduler).
//!
//! The others remain selectable at build time for comparison: SipHash, the standard
//! seeded one; foldhash and aHash, seeded per process.

#[cfg(any(
    all(feature = "hash-sip", feature = "hash-fold"),
    all(feature = "hash-sip", feature = "hash-ahash"),
    all(feature = "hash-fold", feature = "hash-ahash"),
))]
compile_error!("enable at most one of the hash-sip, hash-fold and hash-ahash features");

#[cfg(feature = "hash-sip")]
pub type Hasher = std::collections::hash_map::RandomState;
#[cfg(feature = "hash-fold")]
pub type Hasher = foldhash::fast::RandomState;
#[cfg(feature = "hash-ahash")]
pub type Hasher = ahash::RandomState;
#[cfg(not(any(feature = "hash-sip", feature = "hash-fold", feature = "hash-ahash")))]
pub type Hasher = rustc_hash::FxBuildHasher;

pub type Map<K, V> = std::collections::HashMap<K, V, Hasher>;
