// This file is part of the ArmoniK project
// 
// Copyright (C) ANEO, 2021-2026. All rights reserved.
// 
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY, without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
// 
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

using System.Text.Json;

using NUnit.Framework;

namespace ArmoniK.Core.Adapters.Broker.Tests;

/// <summary>
///   The C# producer must reproduce the vectors generated by the Rust reference implementation.
/// </summary>
[TestFixture]
public class AffinityConformanceTests
{
  private static JsonElement Vectors()
  {
    var dir = new DirectoryInfo(TestContext.CurrentContext.TestDirectory);
    while (dir is not null && !File.Exists(Path.Combine(dir.FullName,
                                                        "ArmoniK.Core.sln")))
    {
      dir = dir.Parent;
    }

    Assert.That(dir,
                Is.Not.Null,
                "repository root not found");
    return JsonDocument.Parse(File.ReadAllText(Path.Combine(dir!.FullName,
                                                            "Broker",
                                                            "conformance",
                                                            "affinity.json")))
                       .RootElement;
  }

  [Test]
  public void HashMatchesReference()
  {
    foreach (var v in Vectors()
               .GetProperty("hash")
               .EnumerateArray())
    {
      Assert.That(Affinity.Hash(v.GetProperty("id")
                                 .GetString()!),
                  Is.EqualTo(v.GetProperty("hash")
                              .GetUInt32()),
                  v.GetProperty("id")
                   .GetString());
    }
  }

  [Test]
  public void EncodeMatchesReference()
  {
    foreach (var v in Vectors()
               .GetProperty("encode")
               .EnumerateArray())
    {
      var size = ulong.Parse(v.GetProperty("size")
                              .GetString()!);
      Assert.That(Affinity.Encode(size),
                  Is.EqualTo(v.GetProperty("code")
                              .GetByte()),
                  $"size {size}");
    }
  }

  [Test]
  public void SelectMatchesReference()
  {
    foreach (var v in Vectors()
               .GetProperty("select")
               .EnumerateArray())
    {
      var name = v.GetProperty("name")
                  .GetString();
      var deps = v.GetProperty("deps")
                  .EnumerateArray()
                  .Select(d => (d.GetProperty("id")
                                 .GetString()!, ulong.Parse(d.GetProperty("size")
                                                             .GetString()!)))
                  .ToList();
      var actual   = Affinity.Select(deps);
      var expected = v.GetProperty("affinity");
      if (expected.ValueKind == JsonValueKind.Null)
      {
        Assert.That(actual,
                    Is.Null,
                    name);
        continue;
      }

      Assert.That(actual,
                  Is.Not.Null,
                  name);
      Assert.Multiple(() =>
                      {
                        Assert.That(actual!.Hashes,
                                    Is.EqualTo(expected.GetProperty("hashes")
                                                       .EnumerateArray()
                                                       .Select(h => h.GetUInt32())),
                                    name);
                        Assert.That(actual.Sizes,
                                    Is.EqualTo(expected.GetProperty("sizes")
                                                       .EnumerateArray()
                                                       .Select(s => s.GetByte())),
                                    name);
                        Assert.That(actual.DepCount,
                                    Is.EqualTo(expected.GetProperty("dep_count")
                                                       .GetUInt16()),
                                    name);
                        Assert.That(actual.TotalSize,
                                    Is.EqualTo(expected.GetProperty("total_size")
                                                       .GetByte()),
                                    name);
                      });
    }
  }
}
