name: Remove Old Branch Artefacts

on:
    schedule:
      - cron: '10 9 * * 1'   # 9:10 on Monday
    workflow_dispatch:

jobs:
  images:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - armonik_pollingagent
          - armonik_control_metrics
          - armonik_control_partition_metrics
          - armonik_control
          - armonik_core_stream_test_worker
          - armonik_core_stream_test_client
          - armonik_core_htcmock_test_worker
          - armonik_core_htcmock_test_client
          - armonik_core_bench_test_worker
          - armonik_core_bench_test_client
    steps:
    - name: Checkout
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

    - name: Set up Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6

    - name: Remove old branch images
      uses: aneoconsulting/ArmoniK.Actions.CleanupArtifacts/remove-images@40131ac01ff60baea9e02612ced7ac9b69916a3d # main
      with:
        org: dockerhubaneo
        image: ${{ matrix.image }}
        user: ${{ secrets.DOCKER_HUB_LOGIN }}
        token: ${{ secrets.DOCKER_HUB_TOKEN }}

  nugets:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        nuget:
          - ArmoniK.Core.Base
    steps:
    - name: Checkout
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

    - name: Set up Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6

    - name: Unlist old branch nugets
      uses: aneoconsulting/ArmoniK.Actions.CleanupArtifacts/unlist-nugets@40131ac01ff60baea9e02612ced7ac9b69916a3d # main
      with:
        nuget: ${{ matrix.nuget }}
        token: ${{ secrets.NUGET_API_KEY }}
