name: Remove Old Branch Artefacts

on:
    schedule:
      - cron: '10 9 * * 1'   # 9:10 on Monday
    workflow_dispatch:

jobs:
  images:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - armonik_pollingagent
          - armonik_control_metrics
          - armonik_control_partition_metrics
          - armonik_control
          - armonik_core_stream_test_worker
          - armonik_core_stream_test_client
          - armonik_core_htcmock_test_worker
          - armonik_core_htcmock_test_client
          - armonik_core_bench_test_worker
          - armonik_core_bench_test_client
    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

    - name: Set up Python
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7

    - name: Remove old branch images
      uses: aneoconsulting/ArmoniK.Actions.CleanupArtifacts/remove-images@c83a887c5a27fef327098a89bce0a28a4e82168d # main
      with:
        org: dockerhubaneo
        image: ${{ matrix.image }}
        user: ${{ secrets.DOCKER_HUB_LOGIN }}
        token: ${{ secrets.DOCKER_HUB_TOKEN }}

  nugets:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        nuget:
          - ArmoniK.Core.Base
    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

    - name: Set up Python
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7

    - name: Unlist old branch nugets
      uses: aneoconsulting/ArmoniK.Actions.CleanupArtifacts/unlist-nugets@c83a887c5a27fef327098a89bce0a28a4e82168d # main
      with:
        nuget: ${{ matrix.nuget }}
        token: ${{ secrets.NUGET_API_KEY }}
